### ISSUE TITLE
Portable version for every release possible?

### ISSUE THREAD

**Issue by dabugen** [Alex313031/Thorium-AVX2#10]
Hi Alex,

thanks for your ongoing efforts with Thorium, I really appreciate it. If I may ask: would it be possible that you add a portable 7ZIP / ZIP version for every release? For example, the latest one only has this annoying mini installer, which silently installs it into AppData, adds 3 links throughout Windows (Desktop, Start Menu, Quick Launch), and even adds several registry entries for the notification helper EXE in the registry for the Windows CLSIDs and the OpenWith dialog. I really don´t want these entries just to extract Thorium from AppData - a simple archive, in addition to the mini installer for every release would be great.

Thanks so much.

**Comment by Alex313031** [comment]
@dabugen Yeah thats exactly what the portable releases are for! I have provided .zips for every release for linux, windows, and windows AVX2 except this one, because it was a hasty interim release with the icon bug, and to test out the user profile and install location change from chromium > thorium. In the future Ill make sure to include a .zip with every release.

 - For now though, what you can do (and you can do this with chromium/chrome too to make a portable release) is use 7-zip and simply extract the thorium_mini_installer. There's a chrome.7z file inside it, and if you extract that you get a folder called Chrome-bin, the contents of which you can just copy into the BIN folder inside the portable releases.
