### ISSUE TITLE
DNS Problem

### ISSUE THREAD

**Issue by Ridianoid** [Alex313031/Thorium-AVX2#116]
Greetings. I use DNS to bypass some site bans in my country, but Thorium ignores the DNS I use through windows. I can't access the sites. There is no such problem in other browsers. How can I fix this?

**Comment by ZonyaZap** [comment]
Check chrome://settings/security and chrome://flags/#enable-async-dns

**Comment by Ridianoid** [comment]
> Check chrome://settings/security and chrome://flags/#enable-async-dns

Thank you. "chrome://settings/security" Secure Dns with Cloudflare fixed my problem.

**Comment by Alex313031** [comment]
@ridoknight Yep, this is because I modified Thorium to enable secure DNS by default, but as you found out, this does not work for all configurations. I have it where it will send a log message when there is a DNS incompatibility, but of course you would only see this if you ran Thorium from the commandline or with --enable-logging.
