### ISSUE TITLE
Netflix doesn't work

### ISSUE THREAD

**Issue by DevSingh07** [Alex313031/Thorium-AVX2#127]
OS: Win 11
Thorium Version [M119.0.6045.214 - 35th Release]

Problem
Netflix Browser Error Code M7121-1331
![239324208-b1146e60-ac71-47fd-beda-ffe3d84cdc07](https://github.com/Alex313031/Thorium-Win-AVX2/assets/108584551/eaaf031d-4046-4164-8770-3ff7d2d21edf)
 
please fix this isse
:)

**Comment by gz83** [comment]
The same or similar questions have been answered many times in issues of different repos. Please make good use of the search function of the issue.

The reason for this problem is that due to financial and other reasons, Thorium failed to obtain official verification from widevine (which requires a lot of money), so audio and video that need to be processed by widevine may not be played properly.
