### ISSUE TITLE
Extension Web Store 

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-AVX2#34]
Hello, i see in extension section of Thorium browser that there is this extension "Web Store" :
Discover great apps, games, extensions and themes for Thorium.

What is the purpose of this extension? and is there a way to disable it please?

**Comment by Alex313031** [comment]
@trimechee This is enabled in all Chromium based browsers. The reason that, and the "Chromium PDF Viewer" and "Google Hangouts" extensions all show up, is because I added a patch to show ALL extensions, not just the ones the user installed. I added the patch for debugging, and just so people can know what is on their system. It is nothing to worry about. Like I said, every chromium based browser has these, it just hides them from the user interface normally.

**Comment by trimechee** [comment]
interesting ! thank you very much for your help :)
