### ISSUE TITLE
is it possible to haves something like this on thorium because if so then i would use thorium over msedge

### ISSUE THREAD

**Issue by Pickymarker** [Alex313031/Thorium-AVX2#78]
is it possible to haves something like this on thorium because if so then i would use thorium over msedge 
![image](https://user-images.githubusercontent.com/74084396/227883140-1cb99623-efbe-49e9-9725-b894885399c0.png)

**Comment by Pickymarker** [comment]
okay and also how do i copy all the userdata stuff from edge to thorium

**Comment by Alex313031** [comment]
@Pickymarker Yeah thorium will have this with M112 and beyond.

IMPORTANT: As per @gz83 note, you can try to migrate your user data dir over. However, *make a backup of the current one!* because edge has alot of stuff that other chromium browser's dont, so the data structures inside the user data dir will be different, and may not play nicely with thorium.
