### ISSUE TITLE
the icon is normal for me

### ISSUE THREAD

**Issue by crocer211** [Alex313031/Thorium-AVX2#8]
i know not a bug but in the release info it says its back but it only shows it when i hover over the icon on the taskbar like when the preview pops up is when it shows it its perfectly normal otherwise

**Comment by Alex313031** [comment]
Hmm. Can you provide a screenshot? And it just came back when I tested it in a win7 and win10 VM.

**Comment by gz83** [comment]
> Hmm. Can you provide a screenshot? And the icon bug just came back when I tested it in a win7 and win10 VM. So I assumed it would look the same for everyone, so Im interested.

The 103 version of the taskbar icon is normal, but the icon in the taskbar thumbnail is not displayed properly.
![image](https://user-images.githubusercontent.com/17492865/164651802-73fdc3d0-92da-4060-ae3f-293573398938.png)

**Comment by Alex313031** [comment]
@gz83 @crocer211 Is Thorium pinned to the taskbar? Unpin it if so, the bug might show up like it does for me on the taskbar. Making a new regular windows build to test.

**Comment by crocer211** [comment]
@Alex313031 unpinned it and its still normal maybe its working fine in windows 11

**Comment by gz83** [comment]
> @gz83 @crocer211 Is Thorium pinned to the taskbar? Unpin it if so, the bug might show up like it does for me on the taskbar. Making a new regular windows build to test.

I don't have Thorium pinned to the taskbar, the taskbar thumbnails are displayed like the above in normal mode and incognito mode.

**Comment by Alex313031** [comment]
@crocer211 @gz83 Thats weird. It has the bug for me in my win7, win 10, and win 11 VMS. And that was with fully uninstalling the previous version and reinstalling the new one, as I always do to test new releases to remove any variables. Im making a new AVX2 release right now, so we'll see if its all good.

The last time this bug showed up, it was because the //chromium/src/chrome/app/theme dir had a PRESUBMIT.py that was set to python2, and needed to be updated to python3, which I did, and then ironically it was converted to python3 upstream just two weeks later. Nothing has changed in that dir upstream or in thorium since then, so Im stumped as to what it is now.

**Comment by Alex313031** [comment]
@gz83 And granted, this is a good thing, yet it is still a bug since it showed up for me and its still showing up for you guys on hover and task switcher. 
Its a good thing though because at least for my users the main icon on the taskbar isnt the ugly yellow warning. And the reason it is that of all things is that is the icon that windows uses when it detects a built in icon on an exe, but there is something wrong with it. If theres no icon at all , it uses the blank box icon which you may have seen at some point with some .exe.

**Comment by gz83** [comment]
> @gz83 And granted, this is a good thing, yet it is still a bug since it showed up for me and its still showing up for you guys on hover and task switcher. Its a good thing though because at least for my users the main icon on the taskbar isnt the ugly yellow warning. And the reason it is that of all things is that is the icon that windows uses when it detects a built in icon on an exe, but there is something wrong with it. If theres no icon at all , it uses the blank box icon which you may have seen at some point with some .exe.

Thank you very much for such a detailed answer, which also gave me a better understanding of the mechanism of the relevant icons. The blank box icon you proposed, I have encountered it before.

**Comment by crocer211** [comment]
@Alex313031 i have not seen that blank box icon before but at least its correct for the taskbar and the actual app icon

**Comment by Alex313031** [comment]
@gz83 @crocer211 Fixed!!! It was a typo in the last time I rebased the chrome_constants file which also sets certain asset names like the logo png name etc. Twas a stupid error. Will upload this fixed build soon. 

On a sad note, this had the win 10 bug come back again, but strangely worked fine on win 11.

**Comment by gz83** [comment]
> @gz83 @crocer211 Fixed!!! It was a typo in the last time I rebased the chrome_constants file which also sets certain asset names like the logo png name etc. Twas a stupid error. Will upload this fixed build soon.
> 
> On a sad note, this had the win 10 bug come back again, but strangely worked fine on win 11.

Does the error on win 10 mean that the browser needs to be opened in compatibility mode? Or is there something wrong with the icon?

**Comment by Alex313031** [comment]
@gz83 @crocer211 Sorry, should have specified. The compatibility bug is back. Lol the universe decided to switch the bugs between these releases.

**Comment by crocer211** [comment]
@Alex313031 well you said it doesnt show it on win 11 well at least im on win 11

**Comment by gz83** [comment]
> @gz83 @crocer211 Sorry, should have specified. The compatibility bug is back. Lol the universe decided to switch the bugs between these releases.

Is this a problem caused by adjusting the compilation parameters?

**Comment by Alex313031** [comment]
@gz83 I don't think so.

**Comment by gz83** [comment]
> @gz83 I don't think so.

Looking forward to further investigation on this issue in the future.

**Comment by Alex313031** [comment]
@gz83 If I can fix the settings search issue and compatibility mode issue I will be happy. The least amount of friction for my users. Because while it doesn't break the browser, who want to have to go dig up the chrome.exe file and set compat mode.
